### ISSUE TITLE
Version 1.0.4 removed all my existing links. 

### ISSUE THREAD

**Issue by mikehopps** [waytab/WayTab#27]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by andrewward2001** [comment]
This one's tough to diagnose due to the way Chrome's storage API works. Did your schedule remain? This could also be related to https://github.com/waytab/WayTab/pull/26/commits/f61ffbd857dfe0a0d13a666e44d6ede3150b7a05.

This could be related to #24 and the advantages of moving away from Chrome's storage API.

**Comment by mikehopps** [comment]
Schedule remained.

**Comment by andrewward2001** [comment]
I think I've figured out what causes this issue. When WayTab is installed, it automatically sets several defaults, but during the update process the user's setup wasn't maintained, and was overwritten by the defaults. This also describes why the schedule and tasks remain, since they don't have defaults.

See https://github.com/waytab/WayTab/blob/master/background/background.js

**Comment by andrewward2001** [comment]
Possibly fixed. Needs testing. https://github.com/waytab/WayTab/commit/0530869f2b39a9a2ed40802faa88ab29f62e6cf0

**Comment by awangg** [comment]
Actually, gonna close for now. Let us know if it the latest patch did the same thing @mikehopps

**Comment by mikehopps** [comment]
1.1.1 didn't remove my links!  Nice work!
