### ISSUE TITLE
Click on the day in the schedule to select letter day

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#61]
This will return some functionality of letter days - users can click on a letter day and then we'll have it cycle normally. It won't count holidays, so they'll have to redo the clicking after like vacations.

**Comment by awangg** [comment]
first step done in https://github.com/waytab/WayTab/commit/0e36792f643548a121d62865a6932d61fd65e2d9

@andrewward2001 would you have any idea on how we can increment the letter day in the chrome storage?

**Comment by awangg** [comment]
it's beautiful

**Comment by andrewward2001** [comment]
well, i dont think its really possible to do it very simply. i think that youd have to save the selected letter day along with the date, and then whenever waytab is opened you check that and update it as needed. because im not really sure how else one might do it otherwise. theres also the background page so you might be able to do it there since i think thats always going when chrome is open (?)

**Comment by awangg** [comment]
completed in https://github.com/waytab/WayTab/commit/bb5b5e8b9223a2361592064f24937adde9c6f6fb
